version = 0.1
[default.deploy.parameters]
stack_name = "rest-api-dynamodb"
resolve_s3 = true
s3_prefix = "rest-api-dynamodb"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
