AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda with spring boot and dynamo db.

Resources:
  AwsDynamodbAPI:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../spring-boot-aws-dynamodb
      Handler: com.sample.microservice.awsdynamodb.StreamLambdaHandler
      Runtime: java11
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Timeout: 180
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        LibraryAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: any

  ConfigLambdaPermission:
    Type: "AWS::Lambda::Permission"
    DependsOn:
      - AwsDynamodbAPI
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AwsDynamodbAPI
      Principal: apigateway.amazonaws.com